### ISSUE TITLE
[BUG] Add navigation buttons to newsletter signup form

### ISSUE THREAD

**Issue by cassgvp** [openresearchcalendar/openresearchcalendar.github.io#57]
**Describe the bug**
The page to sign up to the monthly newsletter has no navigation buttons. Makes it a bit difficult to move around the site.

**To Reproduce**
https://openresearchcalendar.org/email-subscribe

**Expected behaviour**
Page nave buttons as rest of site. 

**Screenshots**

**Proposed solution**
Embed tripetto form: https://tripetto.com/help/articles/how-to-embed-a-form-from-the-studio-into-your-website/

**Comment by b-kennedy0** [comment]
Hi @cassgvp - I too have thought this, I had initially set it up as a normal GitHub page (like our [calendar](https://openresearchcalendar.org/calendar) page) but the embed of the Tripetto form isn't pretty (and useable) on mobile/tablet devices due to the built-in formatting of GitHub Theme Cayman (and probably other themes too, given they are built as a 'blog' type pages). 
The workaround is to have the Tripetto form embedded as an entire HTML page and then once you've completed the form, it should take you to a page that features a 'Home' button. Check out the screenshot:
![image](https://user-images.githubusercontent.com/42816209/120480895-74b66f80-c3a7-11eb-8edf-6e62b98f1b70.png)

**Comment by cassgvp** [comment]
Thank you, @b-kennedy0 . I was sure you had thought about this :)

This site I was involved with used tripetto forms, but with the Beautiful Jekyll theme: https://ohbm.github.io/osr2020/submit/. Renders well on mobile. A slightly more complex theme than Cayman, but also quite a bit prettier...?! I know it quite well, so I'd be happy to clone and fit our content into it, if you'd like to give it a try?

**Comment by b-kennedy0** [comment]
Yes @cassgvp That sounds great! Especially considering our navigation buttons are expanding rapidly. We'll soon to need to add 'Email Newsletter Achive' - perhaps we could have a dropdown for 'Email Newsletter' consisting of: 
- Subscribe
- Unsubscribe
- Archive

**Comment by cassgvp** [comment]
Sounds wonderful :). I'll have a go tonight.

**Comment by cassgvp** [comment]
Had a bit of a play and set the basic structure for the new site using the beautiful Jekyll theme. It's rendered here: https://cassgvp.github.io/orc/ as I couldn't work out how to set a temp domain from our main orc GitHub account. 

I've left one of the tripetto forms we used in place where the orc tripetto forms should go, and a few other place holders. Also copied over the mail archive, but in isn't integrated. Lots of other to-do bits still, but wanted to see what you think before doing too much more.

**Comment by b-kennedy0** [comment]
Hi @cassgvp - I've given it a go at starting from the base template - here is what I have for now: https://bradleykennedy.co.uk/orc

**Comment by b-kennedy0** [comment]
Accidentally closed
