### ISSUE TITLE
'Integromat' rebrand to 'Make' - Doc updates

### ISSUE THREAD

**Issue by b-kennedy0** [openresearchcalendar/openresearchcalendar.github.io#71]
This issue has been opened to track which parts of our documentation need to be updated to reflect the changes from Integromat to their new brand 'Make' https://www.make.com/en

**Comment by EstherPlomp** [comment]
Added a new overview of the schematics workflow to the documents folder and the readme file: https://github.com/openresearchcalendar/openresearchcalendar.github.io/blob/master/Documents/Images/schematic-logos-2-small.png 

So that leaves updating a poster, which I will hopefully get to this weekend!

**Comment by b-kennedy0** [comment]
I've searched our repo and website, thankfully we haven't actually mentioned Integromat so nothing else to update. I feel like I thought this was going to be a much harder task!
